asv_sim:
  ros__parameters:
    platforms.drix_2.model:     drix
    platforms.drix_2.namespace: project11/drix_2

    platforms.drix_2.mru_frame: project11/drix_2/nav

    # Seamounts south of Hawaii
    platforms.drix_2.start_lat: 18.72539
    platforms.drix_2.start_lon: -158.22822
    platforms.drix_2.start_heading: 60.0

